In [102]:

print(__doc__)
import csv
import urllib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

url= "https://raw.githubusercontent.com/avirynd/Bikeshare/master/RidesMinutes.csv?token=AVmUmUm2ljKEwWgVNhcmIk3agE483Dlnks5ZF6fFwA%3D%3D"
ride_min=pd.read_csv(url)


ride_min['Result']=" "
ride_min

Automatically created module for IPython interactive environment

      Unnamed: 0       Date  NumRides  TotalMinutes Result
0              0   1/1/2014       359         16462
1              1   1/1/2015       181          6382
2              2   1/1/2016        98          4039
3              3  1/10/2014       983         13948
4              4  1/10/2015       362         14389
5              5  1/10/2016       133          3504
6              6  1/11/2014       247         12293
7              7  1/11/2015       327          9229
8              8  1/11/2016      1060         10649
9              9  1/12/2014       351         16102
10            10  1/12/2015      1344         14025
11            11  1/12/2016      1090         12543
12            12  1/13/2014      1015         15798
13            13  1/13/2015      1368         15812
14            14  1/13/2016      1033         10033
15            15  1/14/2014      1027         12268
16            16  1/14/2015      1296         14767
17            17  1/14/2016       838         10666
18            18  1/15/2014      1100         12704
19            19  1/15/2015      1229         14341
20            20  1/15/2016       966          9568
21            21  1/16/2014      1097         17151
22            22  1/16/2015      1082         19387
23            23  1/16/2016       162          3083
24            24  1/17/2014      1014         13937
25            25  1/17/2015       319         11673
26            26  1/17/2016       104          2110
27            27  1/18/2014       443         16437
28            28  1/18/2015       275         11394
29            29  1/18/2016       417          6152
...          ...        ...       ...           ...    ...
1069        1069  9/28/2013       612         19800
1070        1070  9/28/2014       376         23302
1071        1071  9/28/2015      1304         15700
1072        1072  9/29/2013       517         15182
1073        1073  9/29/2014      1335         15652
1074        1074  9/29/2015      1408         16809
1075        1075   9/3/2013       597         17351
1076        1076   9/3/2014      1404         15637
1077        1077   9/3/2015      1294         16957
1078        1078  9/30/2013       976         19281
1079        1079  9/30/2014      1304         15149
1080        1080  9/30/2015      1203         12102
1081        1081   9/4/2013       606         17895
1082        1082   9/4/2014      1389         16094
1083        1083   9/4/2015      1129         13542
1084        1084   9/5/2013       677         16070
1085        1085   9/5/2014      1265         19160
1086        1086   9/5/2015       386         12370
1087        1087   9/6/2013       814         22249
1088        1088   9/6/2014       435         13037
1089        1089   9/6/2015       318         12304
1090        1090   9/7/2013       796         32397
1091        1091   9/7/2014       336         14917
1092        1092   9/7/2015       318         12101
1093        1093   9/8/2013       704         30955
1094        1094   9/8/2014      1305         26584
1095        1095   9/8/2015      1333         15474
1096        1096   9/9/2013       769         18543
1097        1097   9/9/2014      1362         22408
1098        1098   9/9/2015      1405         18680

[1099 rows x 5 columns]

In [103]:
ride_min['TotalMinutes'].describe()

count      1099.000000
mean      15199.236579
std       10257.338035
min         542.000000
25%       11843.000000
50%       14680.000000
75%       17518.500000
max      297519.000000
Name: TotalMinutes, dtype: float64

In [104]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier #This is the library that implements the Decision Tree classifier 
from sklearn.model_selection import train_test_split #used to split the dataset into training and test data
#from sklearn.tree import DecisionTreeClassifier

In [105]:
print("ride_min.keys(): {}".format(ride_min.keys()))

ride_min.keys(): Index(['Unnamed: 0', 'Date', 'NumRides', 'TotalMinutes', 'Result'], dtype='object')

In [106]:
#print the shape of the dataset
print("Shape of data: {}".format(ride_min.TotalMinutes.shape))

Shape of data: (1099,)

In [115]:
ride_min['Result_Names']=' '
#1=good
#0=bad day
ride_min.loc[ (ride_min['TotalMinutes'] < 15199), 'Result']= '0'
ride_min.loc[ (ride_min['TotalMinutes'] < 15199), 'Result_Names']= 'bad'
ride_min.loc[ (ride_min['TotalMinutes'] >= 15199), 'Result']= '1'
ride_min.loc[ (ride_min['TotalMinutes'] >= 15199), 'Result_Names']= 'good'

In [116]:
ride_min

      Unnamed: 0       Date  NumRides  TotalMinutes Result Result_Names
0              0   1/1/2014       359         16462      1         good
1              1   1/1/2015       181          6382      0          bad
2              2   1/1/2016        98          4039      0          bad
3              3  1/10/2014       983         13948      0          bad
4              4  1/10/2015       362         14389      0          bad
5              5  1/10/2016       133          3504      0          bad
6              6  1/11/2014       247         12293      0          bad
7              7  1/11/2015       327          9229      0          bad
8              8  1/11/2016      1060         10649      0          bad
9              9  1/12/2014       351         16102      1         good
10            10  1/12/2015      1344         14025      0          bad
11            11  1/12/2016      1090         12543      0          bad
12            12  1/13/2014      1015         15798      1         good
13            13  1/13/2015      1368         15812      1         good
14            14  1/13/2016      1033         10033      0          bad
15            15  1/14/2014      1027         12268      0          bad
16            16  1/14/2015      1296         14767      0          bad
17            17  1/14/2016       838         10666      0          bad
18            18  1/15/2014      1100         12704      0          bad
19            19  1/15/2015      1229         14341      0          bad
20            20  1/15/2016       966          9568      0          bad
21            21  1/16/2014      1097         17151      1         good
22            22  1/16/2015      1082         19387      1         good
23            23  1/16/2016       162          3083      0          bad
24            24  1/17/2014      1014         13937      0          bad
25            25  1/17/2015       319         11673      0          bad
26            26  1/17/2016       104          2110      0          bad
27            27  1/18/2014       443         16437      1         good
28            28  1/18/2015       275         11394      0          bad
29            29  1/18/2016       417          6152      0          bad
...          ...        ...       ...           ...    ...          ...
1069        1069  9/28/2013       612         19800      1         good
1070        1070  9/28/2014       376         23302      1         good
1071        1071  9/28/2015      1304         15700      1         good
1072        1072  9/29/2013       517         15182      0          bad
1073        1073  9/29/2014      1335         15652      1         good
1074        1074  9/29/2015      1408         16809      1         good
1075        1075   9/3/2013       597         17351      1         good
1076        1076   9/3/2014      1404         15637      1         good
1077        1077   9/3/2015      1294         16957      1         good
1078        1078  9/30/2013       976         19281      1         good
1079        1079  9/30/2014      1304         15149      0          bad
1080        1080  9/30/2015      1203         12102      0          bad
1081        1081   9/4/2013       606         17895      1         good
1082        1082   9/4/2014      1389         16094      1         good
1083        1083   9/4/2015      1129         13542      0          bad
1084        1084   9/5/2013       677         16070      1         good
1085        1085   9/5/2014      1265         19160      1         good
1086        1086   9/5/2015       386         12370      0          bad
1087        1087   9/6/2013       814         22249      1         good
1088        1088   9/6/2014       435         13037      0          bad
1089        1089   9/6/2015       318         12304      0          bad
1090        1090   9/7/2013       796         32397      1         good
1091        1091   9/7/2014       336         14917      0          bad
1092        1092   9/7/2015       318         12101      0          bad
1093        1093   9/8/2013       704         30955      1         good
1094        1094   9/8/2014      1305         26584      1         good
1095        1095   9/8/2015      1333         15474      1         good
1096        1096   9/9/2013       769         18543      1         good
1097        1097   9/9/2014      1362         22408      1         good
1098        1098   9/9/2015      1405         18680      1         good

[1099 rows x 6 columns]

In [117]:

X_train, X_test, y_train, y_test = train_test_split(
    ride_min.TotalMinutes, ride_min.Result, stratify=ride_min.Result, random_state=0)

In [122]:
#build the tree using the training data
tree = DecisionTreeClassifier()
X_train=X_train.reshape(-1,1)
X_test=X_test.reshape(-1,1)
tree.fit(X_train, y_train)
#Print accuracy of the model
print("Accuracy on training set: {:.3f}".format(tree.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(tree.score(X_test, y_test)))

Accuracy on training set: 1.000
Accuracy on test set: 0.996

In [132]:
#Build the tree again setting a pre-pruning criterion for maximum depth. See how different depths affect the accuracies.
tree2 = DecisionTreeClassifier(max_depth=4)
tree2.fit(X_train, y_train)

print("Accuracy on training set: {:.3f}".format(tree2.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(tree2.score(X_test, y_test)))

Accuracy on training set: 1.000
Accuracy on test set: 0.996

In [135]:
from sklearn.tree import export_graphviz

export_graphviz(tree, out_file="ride_min_2.dot", class_names=["bad", "good"],
                feature_names=ride_min.Result_Names, impurity=True, filled=True)


#names=np.array(['good','bad'],dtype='<U9')

#print("Sample counts per class:\n{}".format(
 #     {n: v for n, v in zip(ride_min.Result_Names, np.bincount(ride_min.Result))}))

In [137]:
import graphviz

with open("ride_min_2.dot") as f:
    dot_graph = f.read()
display(graphviz.Source(dot_graph))

ModuleNotFoundError: No module named 'graphviz'

In [ ]:
#from IPython.display import Image  
#dot_data = tree.export_graphviz(clf, out_file=None, 
 #                        feature_names=iris.feature_names,  
#                         class_names=iris.target_names,  
#                         filled=True, rounded=True,  
#                         special_characters=True)  
#>> graph = pydotplus.graph_from_dot_data(dot_data)  
#Image(graph.create_png())